name: macOS

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Test cursor geometry
        run: ./macos/test.sh
      - name: Build application
        run: ./macos/build.sh
        env:
          SF_USE_CERT: "0"
